version: '3'
services:
  railsapp:
    build: .
    ports:
      - "3001:3001"
    links:
      - pgdb
  pgdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tamarindo
    ports:
      - "5433:5433"
    volumes:
      - /home/zala/Desktop/WORK/volumes/zalapeach_db:/var/lib/postgresql/data
