version: '3'
services:
  railsapp:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - pgdb
  pgdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tamarindo
    ports:
      - "5433:5432"
