version: '3'
services:
  railsapp:
    build: .
    environment:
      - PGDB_USERNAME
      - PGDB_PASSWORD
    depends_on:
      - pgdb
  pgdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tamarindo
    ports:
      - "5433:5432"
