defaults: &defaults
  SECRET_KEY_BASE: 'your_secret_key_base'
  GOOGLE_CLIENT_ID: 'your_google_client_id'
  GOOGLE_CLIENT_SECRET: 'your_google_client_secret'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

# This file will override the above
<%= IO.read('config/application.local.yml') if File.exists?('config/application.local.yml') %>
